#!/usr/bin/env zsh -r -x -v -e

# What's the one that forces variables to be defined?

# Detect OS, machine, user, dreamhost, etc
# Work vs home?
# remove ".local", etc

# Install dotfiles!

# Concatenate dotfiles? includes? substitutions?

# Copy symlinks

DOTFILES_PATH=$PWD
SHORTHOST=${HOST/\.local/}
# OS detection, default to Linux
case $(uname) in
    FreeBSD)   OS=FreeBSD ;;
    DragonFly) OS=FreeBSD ;;
    OpenBSD)   OS=OpenBSD ;;
    Darwin)    OS=Darwin  ;;
    SunOS)     OS=SunOS   ;;
    *)         OS=Linux   ;;
esac

# for x in y?
rm -f ~/.emacs
rm -f ~/.emacs.d
ln -s -F "$DOTFILES_PATH/emacs.d" ~/.emacs.d
ln -s -f "$DOTFILES_PATH/gemrc" ~/.gemrc
ln -s -f "$DOTFILES_PATH/gitconfig" ~/.gitconfig
ln -s -f "$DOTFILES_PATH/zshrc" ~/.zshrc
ln -s -f "$DOTFILES_PATH/zshenv" ~/.zshenv
mkdir -p ~/bin
ln -s -f "$DOTFILES_PATH"/bin/* ~/bin

# bin/emacs and bin/ec are only for OS X!
if [ "$OS" != Darwin ]; then
    rm -f ~/bin/emacs
    rm -f ~/bin/ec
fi

# Copy based on OS/machine
if [ -f "$DOTFILES_PATH/emacs.$SHORTHOST" ]; then
    ln -s -f "$DOTFILES_PATH/emacs.$SHORTHOST" ~/.emacs.local
fi

# Delete any broken symlinks
rm -f ~/bin/*(-@D) || echo "No broken symlinks in ~/bin"
rm -f ~/*(-@D) || echo "No broken symlinks in ~"

# if Mac, suppress login thing
touch ~/.hushlogin

# Update submodules
git submodule update --init --recursive

# Homebrew on OSX
if [ "$OS" = Darwin ]; then
    which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    which brew || eval "$(/opt/homebrew/bin/brew shellenv)"
    brew doctor || echo "Pay attention to these errors!"
    brew update
    brew bundle install --file ~/dotfiles/Brewfile || echo "Not all brew dependencies were installed"

    ln -sf /opt/homebrew/opt/emacs-plus/Emacs.app /Applications
    # TODO: set up keyboard shortcuts, Terminal preferences

    ./setup-macos

    # Please stop me from committing AWS keys
    git secrets --install -f
fi

# Log in to github and push SSH key
if type "gh" > /dev/null; then
    gh auth login
fi
