#!/usr/bin/env zsh -r -x -v -e
# -*- mode: zsh -*-

# Set macOS preferences
# See https://github.com/pawelgrzybek/dotfiles/blob/master/setup-macos.sh

# Enable Touch ID for sudo
sed "s/^#auth/auth/" /etc/pam.d/sudo_local.template | sudo tee /etc/pam.d/sudo_local

# Set screenshots location
mkdir -p ~/Pictures/Screenshots
defaults write com.apple.screencapture location ~/Pictures/Screenshots

# Auto hide the dock
defaults write com.apple.dock autohide -bool true

# Windows & Apps > Prefer tabs when opening documents
defaults write -globalDomain AppleWindowTabbingMode -string "always"

# Mission Controll > Automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Key repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2

# Delay until repeat
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Txt Input > Correct spelling automatically
defaults write -globalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Txt Input > Capitalise words automatically
defaults write -globalDomain NSAutomaticCapitalizationEnabled -bool false

# Txt Input > Add full stop with double-space
defaults write -globalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Allow terminal to be excempted from XProtect, which makes compiled binaries (e.g. Go tests) run faster
sudo spctl developer-mode enable-terminal

# Skip Gatekeeper for QLMarkdown
xattr -r -d com.apple.quarantine /Applications/QLMarkdown.app

